#!/usr/bin/env bash
# Usage: ts bi
# Summary: Installs new bundles from Gemfile
# Help: This command is used to install new packages from Gemfile
set -e

cd ${_TS_ROOT}/lib
cd console
bundle install
cd -

cd boards
npm i
cd -