#!/usr/bin/env bash
# Usage: btf install-lts
# Summary: Install all requried dependencies on Ubuntu 12.x LTS

set -ex

sudo apt-get install -y python-software-properties

sudo add-apt-repository -y ppa:brightbox/ruby-ng-experimental

sudo apt-add-repository -y ppa:chris-lea/node.js

sudo add-apt-repository -y ppa:chris-lea/nginx-devel

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

sudo apt-get update

sudo tee /etc/apt/preferences.d/nginx-1-5-1000 <<EOF
Package: nginx nginx-common nginx-full nginx-light
Pin: version 1.5*
Pin-Priority: 1000
EOF

sudo apt-get install -y ruby2.0 ruby2.0-dev ruby2.0-doc nodejs mongodb-10gen g++ nginx python-pip

sudo update-alternatives --set ruby /usr/bin/ruby2.0

sudo gem install bundler

sudo pip install supervisor envdir

