#!/usr/bin/env bash
# Usage: btf start
# Summary: Start TeamStatus.TV
# Help: This command is used to start all services

for p in foreman nginx supervisord; do
	command -v "$p" > /dev/null || { echo "Command $p is missing; please install it and try again"; exit 1; }
done

cd ${_BTF_ROOT}

if [ ! -d ${_BTF_ROOT}/libexec/boards/node_modules ] ; then
	echo "Please run \"btf prepare\" first"
	exit 1
fi

if [ $# -eq 0 ] ; then
	supervisord -c libexec/supervisord/supervisord.conf
	echo "Running TeamStatus.TV, use \"btf status\" to monitor it"
	echo ""
	echo "Open http://localhost:57575 to continue"
else
	supervisorctl -c libexec/supervisord/supervisord.conf start $@
fi