#!/usr/bin/env bash
# Usage: btf start
# Summary: Start TeamStatus.TV
# Help: This command is used to start all services

for p in foreman nginx supervisord; do
	command -v "$p" > /dev/null || (echo "Command $p is missing; please install it and try again"; exit 1)
done

cd ${_BTF_ROOT}

if [ $# -eq 0 ] ; then
	supervisord -c libexec/supervisord/supervisord.conf
else
	supervisorctl -c libexec/supervisord/supervisord.conf start $@
fi