#!/usr/bin/env bash
# Usage: ts prepare
# Summary: First command to run after installation
# Help: You need to run this command to refresh dependencies
set -e

cd ${_BTF_ROOT}/lib
cd console
bundle install --deployment --without test,development
cd -

cd boards
npm i
cd -