#!/usr/bin/env bash
# Usage: btf stop
# Summary: Stop TeamStatus.TV
# Help: This command is used to stop all services

for p in supervisorctl; do
	command -v "$p" > /dev/null || (echo "Command $p is missing; please install it and try again"; exit 1)
done

cd ${_BTF_ROOT}

supervisorctl -c etc/supervisord.conf shutdown