#!/usr/bin/env bash
# Usage: btf restart
# Summary: Restart all services
# Help: This command is used to restart of all TeamStatus.TV services

for p in supervisorctl; do
	command -v "$p" > /dev/null || (echo "Command $p is missing; please install it and try again"; exit 1)
done

cd ${_BTF_ROOT}

supervisorctl -c etc/supervisord.conf restart $@